d1 = read.csv("datoseoT.csv")
d2 = read.csv("datosepT.csv")
d3 = read.csv("datosldbT.csv")
d4 = read.csv("datosldbpT.csv")
fact = max(d1$time)
datos = cbind(d1$time/fact,d2$time/fact,d3$time/fact,d4$time/fact)
colnames(datos) = c("Original","Original P","LdB", "LdB P")#c("1","2", "3", "4")
png("ComparacionAlgoritmos.png", width = 1200, height = 1200, units = "px", pointsize = 20)
par(mar=c(6,6,4,2),cex.axis=1.5, cex.lab=1.8, cex.main=1.5)
boxplot(datos,xlab="Algoritmo", ylab="Tiempo de ejecución transformado")
#axis(side=1,at=c("1","2","3","4"), labels=c("Original","Original Paralelizado","Línea de barrido", "Línea de barrido paralelizdo"))
#legend( title="Algoritmos",x="topright", inset=0,legend=c("Original","Original","Línea de barrido", "Línea de barrido paralelizdo"))
