r1 =read.csv('resultsParallel.csv')
r2 =read.csv('resultsE1.csv')
r1 =cbind('Paralelo', r1)
r2 = cbind('Ruleta Selección', r2)
colnames(r1)=c('type','replica','time','gap')
colnames(r2)=c('type','replica','time','gap')
results = rbind(r1,r2)
results$time=NULL
colnames(results)=c('type','replica','time','gap')

png(paste("bxplt_Gap_TipoE1.png",sep=""))
boxplot(results$time ~ results$type, xlab='Tipo', ylab="Tiempo")
graphics.off()
png(paste("bxplt_Tiempo_TipoE1.png",sep=""))
boxplot(results$gap ~ results$type, xlab='Tipo', ylab="Porcentaje de separación")
graphics.off()
